import Head from 'next/head'

import type { ReactNode } from 'react'

import { Flex } from '@components'
import Header from './Header'
import View from '@components/View'
import Footer from './Footer'

interface Props {
  children: ReactNode
}

export default function Layout({ children }: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex direction="column" css={{ minHeight: '100vh' }}>
        <Header />
        <View as="main" css={{ flexGrow: 1 }}>
          {children}
        </View>
        <Footer />
      </Flex>
    </>
  )
}
