import Head from 'next/head'
import { motion } from 'framer-motion'

import { styled } from '@config/stitches'
import { Text, Button, Link, Container } from '@components'
import { TouchableOpacity } from '@components/Button'

const Box = styled('div', {})

export default function LandingPage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box css={{ mx: '$1', my: '$9' }}>asdasd</Box>
      <Link href="/about">
        <Text>navigate to about page</Text>
      </Link>
      <Text size="11" color="primary1">
        asdasd
      </Text>
      <Text as="h1">asdaksd</Text>
      <Container css={{ display: 'grid', gapy: '1rem', mb: '$5' }} size="small">
        <Button as={TouchableOpacity}>asdasd</Button>
        <Button
          radius="pill"
          css={{ $$borderWidth: '0px', $$borderColor: 'transparent' }}
        >
          asdasd
        </Button>
        <Button disabled>disabled</Button>
        <Button loading>loading = true</Button>
        <Button loading={false}>loading = false</Button>
        <Button size="small">asd</Button>
        <Button
          as={motion.a}
          href="#"
          whileTap={{ scale: 0.95 }}
          // transition={{ duration: '200ms' }}
        >
          link
        </Button>
        <Button size="large">asd</Button>
        <Button size="large" variant="ghost">
          ghost
        </Button>
        <Button size="large" variant="secondary">
          secondary
        </Button>
        <Button size="large" variant="secondary" loading as={TouchableOpacity}>
          secondary
        </Button>
        <Button
          size="large"
          variant="primary"
          as={TouchableOpacity}
          radius="10"
          css={{ rt: 0 }}
          disabled
          loading
        >
          primary disabled and loading
        </Button>
        <Button
          size="large"
          variant="primary"
          as={TouchableOpacity}
          radius="10"
          css={{ rt: 0 }}
          loading
          whileHover={{ scale: 1.2 }}
        >
          Get Started loading
        </Button>
        <Button
          size="large"
          variant="primary"
          as={TouchableOpacity}
          radius="pill"
          // disabled
        >
          Get Started
        </Button>
      </Container>
    </>
  )
}
